Repository ArtemTereshkovich/HostOcean, pull requests merged in 2019-03, with the labels that each got.

#43 [HO-16] Implement JWT Authorizathion
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupJwtExtension.cs
  HostOcean/HostOcean.Api/appsettings.template.json
  HostOcean/HostOcean.Application/HostOcean.Application.csproj
  HostOcean/HostOcean.Application/Tokens/Models/Token.cs
  HostOcean/HostOcean.Application/Tokens/Queries/GenerateJwtTokenQuery.cs
  HostOcean/HostOcean.Application/Tokens/Queries/GenerateJwtTokenQueryHandler.cs
Labels: backend, environment

#42 [HO-19] Fluent ValidatIon
  HostOcean/HostOcean.Api/Controllers/PingController.cs
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupAutoMapperExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMVCExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMediatoRExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupSwaggerExtension.cs
  HostOcean/HostOcean.Api/core
  HostOcean/HostOcean.Application/Exceptions/ValidationException.cs
  HostOcean/HostOcean.Application/HostOcean.Application.csproj
  HostOcean/HostOcean.Application/Infrastructure/MapperProfiles/InfrastructureProfile.cs
  HostOcean/HostOcean.Application/Infrastructure/RequestPipelineHandlers/ValidationRequestPipelineHandler.cs
  HostOcean/HostOcean.Application/Ping/Query/Ping/PingQuery.cs
  HostOcean/HostOcean.Application/Ping/Query/Ping/PingQueryHandler.cs
  HostOcean/HostOcean.Application/Ping/Query/PingGreeting/PingGreetingQuery.cs
  HostOcean/HostOcean.Application/Ping/Query/PingGreeting/PingGreetingQueryHandler.cs
  HostOcean/HostOcean.Application/Ping/Query/PingGreeting/PingGreetingQueryValidator.cs
  HostOcean/HostOcean.Persistence/HostOcean.Persistence.csproj
Labels: backend, environment

#47 [HO-25] Implement user registration
  HostOcean/HostOcean.Api/Controllers/UserController.cs
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupIdentityExtension.cs
  HostOcean/HostOcean.Application/Tokens/Queries/GenerateJwtTokenQueryHandler.cs
  HostOcean/HostOcean.Application/User/Create/CreateUserCommand.cs
  HostOcean/HostOcean.Application/User/Create/CreateUserValidator.cs
  HostOcean/HostOcean.Domain/Entities/User.cs
  HostOcean/HostOcean.Infrastructure/HostOcean.Infrastructure.csproj
  HostOcean/HostOcean.Infrastructure/ServiceResult.cs
Labels: backend, feature

#46 [HO-11]Implement Front end react with Home page
  HostOcean/HostOcean.Api/core
  HostOcean/host-ocean/.editorconfig
  HostOcean/host-ocean/package-lock.json
  HostOcean/host-ocean/package.json
  HostOcean/host-ocean/public/favicon.ico
  HostOcean/host-ocean/public/index.html
  HostOcean/host-ocean/public/manifest.json
  HostOcean/host-ocean/src/App.tsx
  HostOcean/host-ocean/src/components/navbar.tsx
  HostOcean/host-ocean/src/index.tsx
  HostOcean/host-ocean/src/react-app-env.d.ts
  HostOcean/host-ocean/src/typings.d.ts
  HostOcean/host-ocean/src/view/Account/AccountModule.tsx
  HostOcean/host-ocean/src/view/Account/AccountRoutes.ts
  HostOcean/host-ocean/src/view/Account/Login/AccountLogin.tsx
  HostOcean/host-ocean/src/view/Account/Register/AccountRegister.tsx
  HostOcean/host-ocean/src/view/Account/Settings/AccountSettings.tsx
  HostOcean/host-ocean/src/view/MainModule.tsx
  HostOcean/host-ocean/src/view/MainPage.tsx
  HostOcean/host-ocean/src/view/MainRoutes.ts
  HostOcean/host-ocean/src/view/Queue/QueueChoose/QueueChoose.tsx
  HostOcean/host-ocean/src/view/Queue/QueueList/QueueList.tsx
  HostOcean/host-ocean/src/view/Queue/QueueModules.tsx
  HostOcean/host-ocean/src/view/Queue/QueueRoutes.ts
  HostOcean/host-ocean/src/view/Statistics/Statistics.tsx
  HostOcean/host-ocean/tsconfig.json
Labels: environment, frontend

#61 [HO-23] Implement exception middleware
  HostOcean/HostOcean.Api/Controllers/UserController.cs
  HostOcean/HostOcean.Api/Filters/MvcExceptionFilter.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMVCExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMediatoRExtension.cs
  HostOcean/HostOcean.Application/Exceptions/AuthorizationException.cs
  HostOcean/HostOcean.Application/Exceptions/NotFoundException.cs
  HostOcean/HostOcean.Application/Exceptions/ValidationException.cs
  HostOcean/HostOcean.Application/User/Create/CreateUserCommand.cs
Labels: backend, environment

#60 [HO-32] Implement Jwt Configuration and refactor project
  HostOcean/HostOcean.Api/Controllers/UserController.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupJwtExtension.cs
  HostOcean/HostOcean.Api/appsettings.Development.json
  HostOcean/HostOcean.Api/appsettings.template.json
  HostOcean/HostOcean.Application/Infrastructure/AppSettings/JwtSettings.cs
  HostOcean/HostOcean.Application/Tokens/Queries/GenerateJwtTokenQuery.cs
  HostOcean/HostOcean.Application/User/Create/CreateUserCommand.cs
  HostOcean/HostOcean.Application/Users/Commands/CreateUser/CreateUserCommand.cs
  HostOcean/HostOcean.Application/Users/Commands/CreateUser/CreateUserValidator.cs
  HostOcean/HostOcean.Application/Users/Models/JwtToken.cs
  HostOcean/HostOcean.Application/Users/Queries/SignInJwtTokenQuery.cs
  HostOcean/HostOcean.Application/Users/Queries/SignInJwtTokenQueryHandler.cs
Labels: architecture design, backend

#69 [HO-36] Impement group seeding with iis api
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISHttpClient.cs
  HostOcean/HostOcean.Persistence/HostOcean.Persistence.csproj
  HostOcean/HostOcean.Persistence/Seed/HostOceanDbInitializer.cs
Labels: backend, feature

#64 [HO-34] Get queue list
  HostOcean/HostOcean.Api/Controllers/QueueController.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupDataBaseExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMVCExtension.cs
  HostOcean/HostOcean.Application/HostOcean.Application.csproj
  HostOcean/HostOcean.Application/Infrastructure/MapperProfiles/LaboratoryWorkProfile.cs
  HostOcean/HostOcean.Application/Infrastructure/MapperProfiles/QueueProfile.cs
  HostOcean/HostOcean.Application/Infrastructure/MapperProfiles/UserProfile.cs
  HostOcean/HostOcean.Application/Infrastructure/MapperProfiles/UserQueueProfile.cs
  HostOcean/HostOcean.Application/LaboratoryWork/Models/LaboratoryWorkModel.cs
  HostOcean/HostOcean.Application/Queue/Commands/TakeQueueCommand.cs
  HostOcean/HostOcean.Application/Queue/Models/QueueModel.cs
  HostOcean/HostOcean.Application/Queue/Queries/GetQueueQuery.cs
  HostOcean/HostOcean.Application/User/Models/UserModel.cs
  HostOcean/HostOcean.Application/UserQueue/Models/UserQueueModel.cs
  HostOcean/HostOcean.Application/Users/Commands/CreateUser/CreateUserCommand.cs
  HostOcean/HostOcean.Application/Users/Queries/SignInJwtTokenQueryHandler.cs
  HostOcean/HostOcean.Domain/Entities/Group.cs
  HostOcean/HostOcean.Domain/Entities/LaboratoryWork.cs
  HostOcean/HostOcean.Domain/Entities/Queue.cs
  HostOcean/HostOcean.Domain/Entities/User.cs
  HostOcean/HostOcean.Domain/Entities/UserQueue.cs
  HostOcean/HostOcean.Persistence/HostOcean.Persistence.csproj
Labels: backend, feature

#71 [HO-37] Implement Api worker using redux + saga
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupCorsExtension.cs
  HostOcean/host-ocean/package-lock.json
  HostOcean/host-ocean/package.json
  HostOcean/host-ocean/src/App.tsx
  HostOcean/host-ocean/src/state/index.js
  HostOcean/host-ocean/src/state/reducers/index.js
  HostOcean/host-ocean/src/state/requests/accountRequests.js
  HostOcean/host-ocean/src/state/requests/index.js
  HostOcean/host-ocean/src/state/sagas/index.js
  HostOcean/host-ocean/src/state/sagas/watchRequest.js
  HostOcean/host-ocean/src/state/services/API.js
  HostOcean/host-ocean/src/view/Account/actions/index.js
  HostOcean/host-ocean/src/view/Account/reducers/pingReducer.js
  HostOcean/host-ocean/src/view/Account/sagas/index.js
  HostOcean/host-ocean/src/view/Account/sagas/pingSaga.js
  HostOcean/host-ocean/src/view/MainPage.tsx
Labels: environment, feature, frontend

#89 [HO-48] Real-time queue updating
  HostOcean/HostOcean.Api/Controllers/UserQueueController.cs
  HostOcean/HostOcean.Api/Hubs/HostOceanHub.cs
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupCorsExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupDependencyInjectionContainerExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupJwtExtension.cs
  HostOcean/HostOcean.Application/Interfaces/Persistence/IRepository.cs
  HostOcean/HostOcean.Application/Interfaces/Persistence/IUnitOfWork.cs
  HostOcean/HostOcean.Application/Interfaces/Persistence/IUserQueueRepository.cs
  HostOcean/HostOcean.Application/LaboratoryWorks/Queries/GetUpcomingLabworksQuery.cs
  HostOcean/HostOcean.Application/UserQueues/Models/UserQueueModel.cs
  HostOcean/HostOcean.Application/UserQueues/Queries/GetUserQueueQuery.cs
  HostOcean/HostOcean.Persistence/Repositories/Repository.cs
  HostOcean/HostOcean.Persistence/Repositories/UnitOfWork.cs
  HostOcean/HostOcean.Persistence/Repositories/UserQueueRepository.cs
  HostOcean/host-ocean/package-lock.json
  HostOcean/host-ocean/package.json
  HostOcean/host-ocean/src/config/index.js
  HostOcean/host-ocean/src/modules/mainpage/actions/queuesActions.js
  HostOcean/host-ocean/src/modules/mainpage/containers/DailyLabworksContainer.js
  HostOcean/host-ocean/src/modules/mainpage/reducers/queuesReducer.js
  HostOcean/host-ocean/src/state/actions/sessionActions.js
  HostOcean/host-ocean/src/state/reducers/configReducer.js
  HostOcean/host-ocean/src/state/reducers/index.js
  HostOcean/host-ocean/src/state/reducers/signalrReducer.js
  HostOcean/host-ocean/src/state/sagas/index.js
  HostOcean/host-ocean/src/state/sagas/signalrConnection.js
  HostOcean/host-ocean/src/state/signalr/index.js
Labels: backend, feature, frontend

#94 [HO-50] Snackbars
  HostOcean/host-ocean/package-lock.json
  HostOcean/host-ocean/package.json
  HostOcean/host-ocean/src/App.js
  HostOcean/host-ocean/src/config/index.js
  HostOcean/host-ocean/src/modules/MainModule.js
  HostOcean/host-ocean/src/modules/account/components/LoginForm/index.js
  HostOcean/host-ocean/src/modules/account/components/LoginForm/styles.js
  HostOcean/host-ocean/src/modules/account/components/RegisterForm/index.js
  HostOcean/host-ocean/src/modules/account/components/RegisterForm/styles.js
  HostOcean/host-ocean/src/modules/authorizedControl/index.js
  HostOcean/host-ocean/src/modules/mainpage/sagas/queueSaga.js
  HostOcean/host-ocean/src/modules/notifications/actions/index.js
  HostOcean/host-ocean/src/modules/notifications/containers/Notifier.js
  HostOcean/host-ocean/src/modules/notifications/reducers/index.js
  HostOcean/host-ocean/src/modules/notifications/reducers/notificationsReducer.js
  HostOcean/host-ocean/src/state/actions/sessionActions.js
  HostOcean/host-ocean/src/state/reducers/index.js
  HostOcean/host-ocean/src/state/sagas/signalrConnection.js
  HostOcean/host-ocean/src/state/sagas/tokenExpirationSaga.js
Labels: frontend
