Repository ArtemTereshkovich/HostOcean, pull requests merged in 2019-02, with the labels that each got.

#4 [HO-2] Environment/init backend
  .gitignore
  .travis.yml
  HostOcean/HostOcean.Api/.dockerignore
  HostOcean/HostOcean.Api/Controllers/ValuesController.cs
  HostOcean/HostOcean.Api/Dockerfile
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/Program.cs
  HostOcean/HostOcean.Api/Properties/launchSettings.json
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/appsettings.Development.json
  HostOcean/HostOcean.Api/appsettings.json
  HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/Dockerfile
  HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/HostOcean.IntegrationTests.csproj
  HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/StubTest.cs
  HostOcean/HostOcean.sln
Labels: backend, environment

#10 [HO-4] Add Swagger for back-end application
  .travis.yml
  HostOcean/HostOcean.Api/Controllers/ValuesController.cs
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/appsettings.Development.json
  HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/HostOcean.IntegrationTests.csproj
Labels: backend, feature

#12 [HO-5] Implement http client to get groups from IIS BSUIR API
  .gitignore
  HostOcean/HostOcean.Api/Infrastructure/BsuirGroupService/IISGroup.cs
  HostOcean/HostOcean.Api/Infrastructure/BsuirGroupService/IISHttpClient.cs
  HostOcean/HostOcean.Api/Infrastructure/BsuirGroupService/IISv1ApiUriBuilder.cs
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/appsettings.Development.json
  HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/Dockerfile
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/HostOcean.UnitTests.csproj
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/IISHttpClientTests.cs
  HostOcean/HostOcean.sln
Labels: backend

#17 [HO-6] Implement Google Calendar Api Client to get group shedule
  .gitignore
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/Infrastructure/GroupScheduleService/GoogleCalendarApiConfiguration.cs
  HostOcean/HostOcean.Api/Infrastructure/GroupScheduleService/GoogleCalendarV3Client.cs
  HostOcean/HostOcean.Api/Infrastructure/GroupScheduleService/GroupEventType.cs
  HostOcean/HostOcean.Api/Infrastructure/GroupScheduleService/IGoogleCalendarClient.cs
  HostOcean/HostOcean.Api/Program.cs
  HostOcean/HostOcean.Api/StartupSettings/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupGoogleCalendarClientExtension.cs
  HostOcean/HostOcean.Api/appsettings.Development.json
  HostOcean/HostOcean.Api/appsettings.json
  HostOcean/HostOcean.Api/appsettings.template.json
Labels: backend

#21 [HO-1] Implement docker compose for CI
  .travis.yml
  HostOcean/.dockerignore
  HostOcean/HostOcean.Api/Dockerfile
  HostOcean/HostOcean.Api/Dockerfile.build
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/StartupSettings/Startup.cs
  HostOcean/HostOcean.Api/appsettings.template.json
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISGroup.cs
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISHttpClient.cs
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISv1ApiUriBuilder.cs
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/GoogleCalendarApiConfiguration.cs
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/GoogleCalendarV3Client.cs
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/GroupEventType.cs
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/IGoogleCalendarClient.cs
  HostOcean/HostOcean.Infrastructure/HostOcean.Infrastructure.csproj
  HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/Dockerfile
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/Dockerfile
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/IISHttpClientTests.cs
  HostOcean/HostOcean.sln
  HostOcean/docker-compose.dcproj
  HostOcean/docker-compose.override.yml
  HostOcean/docker-compose.test.yml
  HostOcean/docker-compose.yml
Labels: architecture design, backend

#19 [HO-8] Create initial database structure
  HostOcean/HostOcean.Api/Dockerfile.build
  HostOcean/HostOcean.Api/Extensions/AppBuilderExtensions.cs
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/StartupSettings/Startup.cs
  HostOcean/HostOcean.Domain/Entities/Entity.cs
  HostOcean/HostOcean.Domain/Entities/Group.cs
  HostOcean/HostOcean.Domain/Entities/Labwork.cs
  HostOcean/HostOcean.Domain/Entities/Place.cs
  HostOcean/HostOcean.Domain/Entities/Queue.cs
  HostOcean/HostOcean.Domain/Entities/User.cs
  HostOcean/HostOcean.Domain/HostOcean.Domain.csproj
  HostOcean/HostOcean.Persistence/Configurations/GroupConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/LabworkConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/PlaceConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/QueuesConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/UserConfiguration.cs
  HostOcean/HostOcean.Persistence/HostOcean.Persistence.csproj
  HostOcean/HostOcean.Persistence/HostOceanDbContext.cs
  HostOcean/HostOcean.Persistence/Interfaces/IRepository.cs
  HostOcean/HostOcean.Persistence/Interfaces/IUnitOfWork.cs
  HostOcean/HostOcean.Persistence/Migrations/20190215142311_Initial.Designer.cs
  HostOcean/HostOcean.Persistence/Migrations/20190215142311_Initial.cs
  HostOcean/HostOcean.Persistence/Migrations/HostOceanDbContextModelSnapshot.cs
  HostOcean/HostOcean.Persistence/Repositories/Repository.cs
  HostOcean/HostOcean.Persistence/Repositories/UnitOfWork.cs
  HostOcean/HostOcean.Persistence/Seed/HostOceanDbInitializer.cs
  HostOcean/HostOcean.sln
Labels: architecture design, backend

#24 [HO-12] Implement Unit Tests for project (1 test for google api in additional)
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISGroup.cs
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISHttpClient.cs
  HostOcean/HostOcean.Infrastructure/BsuirGroupService/IISv1ApiUriBuilder.cs
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/GoogleCalendarV3Client.cs
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/HostOcean.UnitTests.csproj
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/IISHttpClientTests.cs
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/Infrastructure/BsuirGroupSchedule/IISGroupAttributesTests.cs
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/Infrastructure/BsuirGroupSchedule/IISv1ApiUriBuilderTests.cs
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/Infrastructure/GroupSheduleService/GoogleCalendarV3ClientTests.cs
Labels: backend, feature

#27 [HO-13] Refactor Domain layer
  HostOcean/HostOcean.Api/StartupSettings/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupDataBaseContextInitializerExtension.cs
  HostOcean/HostOcean.Domain/Entities/Group.cs
  HostOcean/HostOcean.Domain/Entities/LaboratorySubGroup.cs
  HostOcean/HostOcean.Domain/Entities/LaboratoryWork.cs
  HostOcean/HostOcean.Domain/Entities/Labwork.cs
  HostOcean/HostOcean.Domain/Entities/Queue.cs
  HostOcean/HostOcean.Domain/Entities/User.cs
  HostOcean/HostOcean.Domain/Entities/UserQueue.cs
  HostOcean/HostOcean.Domain/Entities/UserSubGroup.cs
  HostOcean/HostOcean.Persistence/Configurations/GroupConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/LaboratoryWorkConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/LabworkConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/QueuesConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/UserConfiguration.cs
  HostOcean/HostOcean.Persistence/Configurations/UserQueueConfiguration.cs
  HostOcean/HostOcean.Persistence/HostOceanDbContext.cs
  HostOcean/HostOcean.Persistence/Interfaces/IUnitOfWork.cs
  HostOcean/HostOcean.Persistence/Migrations/20190218091651_InitialMigration.Designer.cs
  HostOcean/HostOcean.Persistence/Migrations/20190218091651_InitialMigration.cs
  HostOcean/HostOcean.Persistence/Migrations/HostOceanDbContextModelSnapshot.cs
  HostOcean/HostOcean.Persistence/Repositories/UnitOfWork.cs
  HostOcean/HostOcean.Persistence/Seed/HostOceanDbInitializer.cs
Labels: architecture design, backend

#30 [HO-14] Implement MediatR for Asp Net Core
  HostOcean/HostOcean.Api/Controllers/BaseController.cs
  HostOcean/HostOcean.Api/Controllers/PingController.cs
  HostOcean/HostOcean.Api/Controllers/ValuesController.cs
  HostOcean/HostOcean.Api/Dockerfile.build
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/Program.cs
  HostOcean/HostOcean.Api/Properties/launchSettings.json
  HostOcean/HostOcean.Api/StartupSettings/Startup.cs
  HostOcean/HostOcean.Application/HostOcean.Application.csproj
  HostOcean/HostOcean.Application/Ping/Model/Pong.cs
  HostOcean/HostOcean.Application/Ping/Query/PingGreetingQuery.cs
  HostOcean/HostOcean.Application/Ping/Query/PingGreetingQueryHandler.cs
  HostOcean/HostOcean.Application/Ping/Query/PingQuery.cs
  HostOcean/HostOcean.Application/Ping/Query/PingQueryHandler.cs
  HostOcean/HostOcean.Persistence/HostOcean.Persistence.csproj
  HostOcean/HostOcean.Persistence/Migrations/20190219013936_Initial.Designer.cs
  HostOcean/HostOcean.Persistence/Migrations/20190219013936_Initial.cs
  HostOcean/HostOcean.Persistence/Seed/HostOceanDbInitializer.cs
  HostOcean/HostOcean.sln
  HostOcean/docker-compose.dcproj
  HostOcean/docker-compose.override.yml
  HostOcean/docker-compose.yml
Labels: architecture design, backend, environment

#33 [HO-15] Add AutoMapper
  HostOcean/HostOcean.Api/HostOcean.Api.csproj
  HostOcean/HostOcean.Api/Program.cs
  HostOcean/HostOcean.Api/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/Startup.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupAutoMapperExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupDataBaseContextInitializerExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupDataBaseExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupDependencyInjectionContainerExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupGoogleCalendarClientExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupHttpClientsExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupIdentityExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMVCExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupMediatoRExtension.cs
  HostOcean/HostOcean.Api/StartupSettings/StartupExtensions/StartupSwaggerExtension.cs
  HostOcean/HostOcean.Application/HostOcean.Application.csproj
  HostOcean/HostOcean.Application/MapperProfiles/InfrastructureProfile.cs
  HostOcean/HostOcean.Domain/Entities/User.cs
  HostOcean/HostOcean.Domain/HostOcean.Domain.csproj
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/GoogleCalendarV3Client.cs
  HostOcean/HostOcean.Infrastructure/GroupScheduleService/GroupEventTypeConstant.cs
  HostOcean/HostOcean.Persistence/Migrations/20190219013936_Initial.cs
  HostOcean/HostOcean.Persistence/Seed/HostOceanDbInitializer.cs
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/Infrastructure/BsuirGroupSchedule/IISv1ApiUriBuilderTests.cs
  HostOcean/HostOcean.Tests/HostOcean.UnitTests/Infrastructure/GroupSheduleService/GoogleCalendarV3ClientTests.cs
  HostOcean/docker-compose.override.yml
Labels: architecture design, backend, environment

#36 [HO-17]Update docker compose and create new migration for db
  HostOcean/HostOcean.Api/Dockerfile
  HostOcean/HostOcean.Persistence/HostOcean.Persistence.csproj
  HostOcean/HostOcean.Persistence/Migrations/20190226080635_InitialMigration.Designer.cs
  HostOcean/HostOcean.Persistence/Migrations/20190226080635_InitialMigration.cs
  HostOcean/HostOcean.Persistence/Seed/HostOceanDbInitializer.cs
  HostOcean/docker-compose.override.yml
  HostOcean/docker-compose.test.yml
  HostOcean/docker-compose.yml
Labels: backend, environment
